// <auto-generated />
using System;
using D_P.Infrastucture.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace D_P.Infrastucture.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230214025049_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("D_B.Core.Domain.Entities.Citas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Causa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripccionEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NombreDoctorID")
                        .HasColumnType("int");

                    b.Property<int?>("NombrePacienteID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NombreDoctorID");

                    b.HasIndex("NombrePacienteID");

                    b.ToTable("Citas", (string)null);
                });

            modelBuilder.Entity("D_B.Core.Domain.Entities.Medicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cedula")
                        .HasColumnType("int");

                    b.Property<string>("FotoFileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medicos", (string)null);
                });

            modelBuilder.Entity("D_B.Core.Domain.Entities.Pacientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cedula")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha_Nacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Fumador")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("alergias")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("D_B.Core.Domain.Entities.PruebaLaboratorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Prueba_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PruebaLaboratorios", (string)null);
                });

            modelBuilder.Entity("D_B.Core.Domain.Entities.Resultados_Laboratorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("PacienteID")
                        .HasColumnType("int");

                    b.Property<int>("PruebaLab")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteID");

                    b.HasIndex("PruebaLab");

                    b.ToTable("Resultados_Laboratorios", (string)null);
                });

            modelBuilder.Entity("D_B.Core.Domain.Entities.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rol")
                        .HasColumnType("bit");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("D_B.Core.Domain.Entities.Citas", b =>
                {
                    b.HasOne("D_B.Core.Domain.Entities.Medicos", "medico")
                        .WithMany("citas")
                        .HasForeignKey("NombreDoctorID");

                    b.HasOne("D_B.Core.Domain.Entities.Pacientes", "paciente")
                        .WithMany("citas")
                        .HasForeignKey("NombrePacienteID");

                    b.Navigation("medico");

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("D_B.Core.Domain.Entities.Resultados_Laboratorio", b =>
                {
                    b.HasOne("D_B.Core.Domain.Entities.Pacientes", "paciente")
                        .WithMany("resultados_Laboratorio")
                        .HasForeignKey("PacienteID");

                    b.HasOne("D_B.Core.Domain.Entities.PruebaLaboratorio", "pruebaLaboratorio")
                        .WithMany("resultados_Laboratorios")
                        .HasForeignKey("PruebaLab")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paciente");

                    b.Navigation("pruebaLaboratorio");
                });

            modelBuilder.Entity("D_B.Core.Domain.Entities.Medicos", b =>
                {
                    b.Navigation("citas");
                });

            modelBuilder.Entity("D_B.Core.Domain.Entities.Pacientes", b =>
                {
                    b.Navigation("citas");

                    b.Navigation("resultados_Laboratorio");
                });

            modelBuilder.Entity("D_B.Core.Domain.Entities.PruebaLaboratorio", b =>
                {
                    b.Navigation("resultados_Laboratorios");
                });
#pragma warning restore 612, 618
        }
    }
}
